<h1>Books table</h1>

<div class="alert alert-info"><?=\Library\Session::getFlash()?></div>

<div class="table-responsive">
    <table class="table" >
        <tr>
            <th>ID</th>
            <th>Title</th>
            <th>Price</th>
            <th>Active</th>
            <th>Actions</th>
        </tr>

        <?php foreach ($books as $book) : ?>
            <tr>
                <td><?=$book['id']?></td>
                <td><?=$book['title']?></td>
                <td><?=$book['price']?></td>
                <td><?=$book['status']?></td>
                <td>
                    <a href="/admin/books/edit/<?=$book['id']?>" title="Edit"><span class="glyphicon glyphicon-edit"></span></a>
                    <a href="/admin/books/remove/<?=$book['id']?>" title="Remove" onclick="return confirm('Are you sure?')"><span class="glyphicon glyphicon-remove"></span></a>
                </td>
            </tr>
        <?php endforeach; ?>

    </table>
</div>



