<h1>Books in cart</h1>

<div class="books">
    <?php if (!$books) : ?>

        Empty :(

    <?php else:?>

        <?php foreach ($books as $book) : ?>
            <div class="book-item">
                Title:  <?=$book['title']?><br>
                Price:  <?=$book['price']?><br>
                <a href="#">Remove from cart</a>
            </div>
        <?php endforeach; ?>

    <?php endif;?>
</div>


