<h1>Contact form</h1>
<script src="/js/scripts.js"></script>
<style>
    .alert-info:empty {
        display:none
    }
</style>

<div class="alert alert-info"><?=\Library\Session::getFlash()?></div>
<form method="post">
    <div class="form-group">
        <input  class="form-control" id="username" type="text" name="username" value="<?=$form->username?>">
    </div>

    <div class="form-group">
        <input class="form-control" id="email" type="email" name="email" value="<?=$form->email?>">
    </div>

    <div class="form-group">
        <textarea class="form-control" id="message" name="message" id="" cols="30" rows="10"><?=$form->message?></textarea>
    </div>

    <button class="btn btn-info">Go</button>



</form>