<h1><?=$page['title']?></h1>
<?=$page['content']?>


<a href="http://google.com" id="test">Goooo</a>

<button onclick="this.style.display = 'none'">Click</button>
<script>
    function my() {
        var element = document.getElementById('test');
       // alert(1);
        element.href = '/contact-us';
        element.style.backgroundColor = 'yellow';
        console.log(element);
    }

</script>
