<b><?=Session::getFlash()?></b>
<form action="" method="post">
    Title: <input type="text" name="title" value="<?=$form->title?>"> <br>
    Price: <input type="text" name="price" value="<?=$form->price?>"> <br>
    Description:
    <textarea name="description"><?=$form->description?></textarea> <br>
    Style: <b>TODO</b> <br>
    Active: <input type="checkbox" name="status" <?=$form->status ? 'checked' : '' ?>> <br>
    <button>Go</button>
</form>