<h1>Books</h1>

<div class="row">
    <?php foreach ($books as $book) : ?>
        <div class="col-md-4 col-lg-2 col-sm-12">
            Title:  <?=$book['title']?><br>
            Price:  <?=$book['price']?><br>
            <img src="<?=$book['image']?>" alt="" class="img-responsive"><br>
            <a href="/book-<?=$book['id']?>.html">Details</a>
        </div>
    <?php endforeach; ?>
</div>


